dataset_regions:
    - !!python/tuple ["singlemu_tot", "singlemu_tot"]
    - !!python/tuple ["doublemu_tot", "doublemu_tot"]
    - !!python/tuple ["triplemu_tot", "triplemu_tot"]
processes:
    - "singlemu_pass"
    - "doublemu_pass"
    - "triplemu_pass"
proc_id:
    singlemu_pass: 1
    doublemu_pass: 2
    triplemu_pass: 3
parameters:
    eff:    ["extArg", "0.5", "[0,1.5]"]
    mueff:  ["extArg", "1",   "[0,2]"]
    eff1mu: ["rateParam", "singlemu_tot", "*", "1/(@0-(1-@1))",   "eff,mueff"]
    eff2mu: ["rateParam", "doublemu_tot", "*", "1/(@0-(1-@1)*2)", "eff,mueff"]
    eff3mu: ["rateParam", "triplemu_tot", "*", "1/(@0-(1-@1)*3)", "eff,mueff"]
systematics:
dataset_conv:
    SingleMuon: "singlemu_tot"
    DoubleMuon: "doublemu_tot"
    TripleMuon: "triplemu_tot"
region_conv:
    SingleMuon: "singlemu_tot"
    DoubleMuon: "doublemu_tot"
    TripleMuon: "triplemu_tot"
process_conv:
    SingleMuon_Passed: "singlemu_pass"
    DoubleMuon_Passed: "doublemu_pass"
    TripleMuon_Passed: "triplemu_pass"
    SingleMuon_Total: "singlemu_tot"
    DoubleMuon_Total: "doublemu_tot"
    TripleMuon_Total: "triplemu_tot"
dataset_region_process_conv:
    !!python/tuple ["SingleMuon", "SingleMuon",              "SingleMuon"]: !!python/tuple ["SingleMuon", "SingleMuon", "SingleMuon_Drop"]
    !!python/tuple ["SingleMuon", "DoubleMuon",              "SingleMuon"]: !!python/tuple ["DoubleMuon", "DoubleMuon", "DoubleMuon_Drop"]
    !!python/tuple ["SingleMuon", "TripleMuon",              "SingleMuon"]: !!python/tuple ["TripleMuon", "TripleMuon", "TripleMuon_Drop"]
    !!python/tuple ["SingleMuon", "SingleMuon_METTrigger",   "SingleMuon"]: !!python/tuple ["SingleMuon", "SingleMuon", "SingleMuon_Passed"]
    !!python/tuple ["SingleMuon", "DoubleMuon_METTrigger",   "SingleMuon"]: !!python/tuple ["DoubleMuon", "DoubleMuon", "DoubleMuon_Passed"]
    !!python/tuple ["SingleMuon", "TripleMuon_METTrigger",   "SingleMuon"]: !!python/tuple ["TripleMuon", "TripleMuon", "TripleMuon_Passed"]
    !!python/tuple ["SingleMuon", "SingleMuon_noMETTrigger", "SingleMuon"]: !!python/tuple ["SingleMuon", "SingleMuon", "SingleMuon_Total"]
    !!python/tuple ["SingleMuon", "DoubleMuon_noMETTrigger", "SingleMuon"]: !!python/tuple ["DoubleMuon", "DoubleMuon", "DoubleMuon_Total"]
    !!python/tuple ["SingleMuon", "TripleMuon_noMETTrigger", "SingleMuon"]: !!python/tuple ["TripleMuon", "TripleMuon", "TripleMuon_Total"]
