dataset_regions:
    - !!python/tuple ["MET", "monojet"]
    - !!python/tuple ["MET", "singlemu"]
    - !!python/tuple ["MET", "doublemu"]
processes:
    - "znunu"
    - "zmumu"
    - "wlnu"
    - "qcd"
    - "bkg"
systematics:
    - "lumi"
    - "d1k_ew"
    - "d2k_ew_w"
    - "d2k_ew_z"
    - "d3k_ew_w"
    - "d3k_ew_z"
    - "metTrigSF"
    - "muonId"
    - "muonIso"
    - "muonTrack"
    # - "muonTrig"
    - "pileup"
    - "jer"
    - "jes"
    - "unclust"
dataset_conv:
    MET: "MET"
    SingleMuon: "SingleMuon"
region_conv:
    Monojet: "monojet"
    SingleMuon: "singlemu"
    DoubleMuon: "doublemu"
process_conv:
    ZJetsToNuNu: "znunu"
    DYJetsToMuMu: "zmumu"
    WJetsToENu: "wlnu"
    WJetsToMuNu: "wlnu"
    WJetsToTauNu: "wlnu"
    QCD: "qcd"
    TTJets: "bkg"
    Diboson: "bkg"
    DYJetsToEE: "bkg"
    DYJetsToTauTau: "bkg"
    EWKV2Jets: "bkg"
    SingleTop: "bkg"
    G1Jet: "bkg"
    VGamma: "bkg"
    MET: "MET"
    SingleMuon: "SingleMuon"
