dataset_regions:
    - !!python/tuple ["MET", "monojet"]
    - !!python/tuple ["MET", "singlemu"]
    - !!python/tuple ["MET", "doublemu"]
    - !!python/tuple ["SingleElectron", "singleele"]
    - !!python/tuple ["SingleElectron", "doubleele"]
processes:
    - "znunu"
    - "zmumu"
    - "zee"
    - "wlnu"
    - "qcd"
    - "bkg"
proc_id:
    znunu: 0
    zmumu: 1
    zee: 2
    wlnu: 3
    qcd: 4
    bkg: 5
parameters:
    tf_wlnu: ["rateParam", "*", "wlnu", "1", "[0,2]"]
    r_z:     ["rateParam", "*", "z*",   "1", "[0,2]"]
systematics:
    - "lumi"
    - "d1k_qcd"
    - "d2k_qcd"
    - "d3k_qcd"
    - "d1k_ew"
    - "d2k_ew_w"
    - "d2k_ew_z"
    - "d3k_ew_w"
    - "d3k_ew_z"
    - "dk_mix"
    - "metTrigSF"
    - "muonId"
    - "muonIso"
    - "muonTrack"
    - "pileup"
    - "jesTotal"
    - "jer"
    - "unclust"
    - "eleIdIso"
    - "eleReco"
    - "eleTrig"
dataset_conv:
    MET: "MET"
    SingleMuon: "SingleMuon"
    SingleElectron: "SingleElectron"
region_conv:
    Monojet: "monojet"
    SingleMuon: "singlemu"
    DoubleMuon: "doublemu"
    SingleElectron: "singleele"
    DoubleElectron: "doubleele"
process_conv:
    ZJetsToNuNu: "znunu"
    DYJetsToMuMu: "zmumu"
    DYJetsToEE: "zee"
    WJetsToENu: "wlnu"
    WJetsToMuNu: "wlnu"
    WJetsToTauNu: "wlnu"
    QCD: "qcd"
    TTJets: "bkg"
    Diboson: "bkg"
    DYJetsToTauTau: "bkg"
    EWKV2Jets: "bkg"
    SingleTop: "bkg"
    G1Jet: "bkg"
    VGamma: "bkg"
    MET: "MET"
    SingleMuon: "SingleMuon"
    SingleElectron: "SingleElectron"
apply: {}
