dataset_regions:
    - !!python/tuple ["singleele", "singleele_pass"]
    - !!python/tuple ["singleele", "singleele_fail"]
    - !!python/tuple ["doubleele", "doubleele_pass"]
    - !!python/tuple ["doubleele", "doubleele_fail"]
    - !!python/tuple ["tripleele", "tripleele_pass"]
    - !!python/tuple ["tripleele", "tripleele_fail"]
processes:
    - "singleele_tot"
    - "doubleele_tot"
    - "tripleele_tot"
proc_id:
    singleele_tot: 1
    doubleele_tot: 2
    tripleele_tot: 3
parameters:
    eff:    ["rateParam", "singleele_pass", "singleele_tot", "0.75",         "[0,1.5]"]
    eleeff: ["rateParam", "singleele_pass", "singleele_tot", "0.75",         "[0,1.5]"]
    ineff1: ["rateParam", "singleele_fail", "singleele_tot", "(1-@0*@1)",    "eff,eleeff"]
    eff2:   ["rateParam", "doubleele_pass", "doubleele_tot", "@0*@1**2",     "eff,eleeff"]
    ineff2: ["rateParam", "doubleele_fail", "doubleele_tot", "(1-@0*@1**2)", "eff,eleeff"]
    eff3:   ["rateParam", "tripleele_pass", "tripleele_tot", "@0*@1**3",     "eff,eleeff"]
    ineff3: ["rateParam", "tripleele_fail", "tripleele_tot", "(1-@0*@1**3)", "eff,eleeff"]
systematics:
dataset_conv:
    SingleElectron: "singleele"
    DoubleElectron: "doubleele"
    TripleElectron: "tripleele"
region_conv:
    SingleElectron_METTrigger: "singleele_pass"
    DoubleElectron_METTrigger: "doubleele_pass"
    TripleElectron_METTrigger: "tripleele_pass"
    SingleElectron_FailMETTrigger: "singleele_fail"
    DoubleElectron_FailMETTrigger: "doubleele_fail"
    TripleElectron_FailMETTrigger: "tripleele_fail"
process_conv:
    SingleElectron: "singleele"
    DoubleElectron: "doubleele"
    TripleElectron: "tripleele"
    SingleElectron_Total: "singleele_tot"
    DoubleElectron_Total: "doubleele_tot"
    TripleElectron_Total: "tripleele_tot"
dataset_region_process_conv:
    !!python/tuple ["SingleElectron", "SingleElectron",              "SingleElectron"]: !!python/tuple ["SingleElectron", "SingleElectron",            "SingleElectron_Drop"]
    !!python/tuple ["SingleElectron", "DoubleElectron",              "SingleElectron"]: !!python/tuple ["DoubleElectron", "DoubleElectron",            "DoubleElectron_Drop"]
    !!python/tuple ["SingleElectron", "TripleElectron",              "SingleElectron"]: !!python/tuple ["TripleElectron", "TripleElectron",            "TripleElectron_Drop"]
    !!python/tuple ["SingleElectron", "SingleElectron_noMETTrigger", "SingleElectron"]: !!python/tuple ["SingleElectron", "SingleElectron_METTrigger", "SingleElectron_Total"]
    !!python/tuple ["SingleElectron", "DoubleElectron_noMETTrigger", "SingleElectron"]: !!python/tuple ["DoubleElectron", "DoubleElectron_METTrigger", "DoubleElectron_Total"]
    !!python/tuple ["SingleElectron", "TripleElectron_noMETTrigger", "SingleElectron"]: !!python/tuple ["TripleElectron", "TripleElectron_METTrigger", "TripleElectron_Total"]
    !!python/tuple ["SingleElectron", "SingleElectron_METTrigger",   "SingleElectron"]: !!python/tuple ["SingleElectron", "SingleElectron_METTrigger", "SingleElectron"]
    !!python/tuple ["SingleElectron", "DoubleElectron_METTrigger",   "SingleElectron"]: !!python/tuple ["DoubleElectron", "DoubleElectron_METTrigger", "DoubleElectron"]
    !!python/tuple ["SingleElectron", "TripleElectron_METTrigger",   "SingleElectron"]: !!python/tuple ["TripleElectron", "TripleElectron_METTrigger", "TripleElectron"]
apply:
    SingleElectron:
        levels: ["dataset", "region", "process"]
        new_levels: ["SingleElectron", "SingleElectron_FailMETTrigger", "SingleElectron"]
        args:
            - ["SingleElectron", "SingleElectron_METTrigger", "SingleElectron_Total"]
            - ["SingleElectron", "SingleElectron_METTrigger", "SingleElectron"]
        formula: "tot, pas: tot - pas"
    DoubleElectron:
        levels: ["dataset", "region", "process"]
        new_levels: ["DoubleElectron", "DoubleElectron_FailMETTrigger", "DoubleElectron"]
        args:
            - ["DoubleElectron", "DoubleElectron_METTrigger", "DoubleElectron_Total"]
            - ["DoubleElectron", "DoubleElectron_METTrigger", "DoubleElectron"]
        formula: "tot, pas: tot - pas"
    TripleElectron:
        levels: ["dataset", "region", "process"]
        new_levels: ["TripleElectron", "TripleElectron_FailMETTrigger", "TripleElectron"]
        args:
            - ["TripleElectron", "TripleElectron_METTrigger", "TripleElectron_Total"]
            - ["TripleElectron", "TripleElectron_METTrigger", "TripleElectron"]
        formula: "tot, pas: tot - pas"
    SingleElectron_Total:
        levels: ["dataset", "region", "process"]
        new_levels: ["SingleElectron", "SingleElectron_FailMETTrigger", "SingleElectron_Total"]
        args:
            - ["SingleElectron", "SingleElectron_METTrigger", "SingleElectron_Total"]
        formula: "tot: tot"
    DoubleElectron_Total:
        levels: ["dataset", "region", "process"]
        new_levels: ["DoubleElectron", "DoubleElectron_FailMETTrigger", "DoubleElectron_Total"]
        args:
            - ["DoubleElectron", "DoubleElectron_METTrigger", "DoubleElectron_Total"]
        formula: "tot: tot"
    TripleElectron_Total:
        levels: ["dataset", "region", "process"]
        new_levels: ["TripleElectron", "TripleElectron_FailMETTrigger", "TripleElectron_Total"]
        args:
            - ["TripleElectron", "TripleElectron_METTrigger", "TripleElectron_Total"]
        formula: "tot: tot"
