dataset_regions:
    - !!python/tuple ["MET", "monojet"]
    - !!python/tuple ["MET", "monojetqcd"]
    - !!python/tuple ["MET", "singlemu"]
    - !!python/tuple ["MET", "singlemuqcd"]
processes:
    - "znunu"
    - "zmumu"
    - "wlnu"
    - "qcd"
    - "bkg"
proc_id:
    znunu: 1
    zmumu: 2
    wlnu: 3
    qcd: 0
    bkg: 4
systematics:
    - "lumi"
    - "d1k_ew"
    - "d2k_ew_w"
    - "d2k_ew_z"
    - "d3k_ew_w"
    - "d3k_ew_z"
    - "metTrigSF"
    - "muonId"
    - "muonIso"
    - "muonTrack"
    - "pileup"
    - "jesAbsoluteStat"
    - "jesAbsoluteScale"
    - "jesAbsoluteMPFBias"
    - "jesFragmentation"
    - "jesSinglePionECAL"
    - "jesSinglePionHCAL"
    - "jesFlavorQCD"
    - "jesTimePtEta"
    - "jesRelativeJEREC1"
    - "jesRelativeJEREC2"
    - "jesRelativeJERHF"
    - "jesRelativePtBB"
    - "jesRelativePtEC1"
    - "jesRelativePtEC2"
    - "jesRelativePtHF"
    - "jesRelativeBal"
    - "jesRelativeFSR"
    - "jesRelativeStatFSR"
    - "jesRelativeStatEC"
    - "jesRelativeStatHF"
    - "jesPileUpDataMC"
    - "jesPileUpPtRef"
    - "jesPileUpPtBB"
    - "jesPileUpPtEC1"
    - "jesPileUpPtEC2"
    - "jesPileUpPtHF"
    - "jesTotal"
    - "jer"
    - "unclust"
    - "eleIdIso"
    - "eleReco"
    - "eleTrig"
dataset_conv:
    MET: "MET"
    SingleMuon: "SingleMuon"
    SingleElectron: "SingleElectron"
region_conv:
    Monojet: "monojet"
    MonojetQCD: "monojetqcd"
    SingleMuon: "singlemu"
    SingleMuonQCD: "singlemuqcd"
    DoubleMuon: "doublemu"
    SingleElectron: "singleele"
    DoubleElectron: "doubleele"
process_conv:
    ZJetsToNuNu: "znunu"
    DYJetsToMuMu: "zmumu"
    DYJetsToEE: "zee"
    WJetsToENu: "wlnu"
    WJetsToMuNu: "wlnu"
    WJetsToTauNu: "wlnu"
    QCD: "qcd"
    TTJets: "bkg"
    Diboson: "bkg"
    DYJetsToTauTau: "bkg"
    EWKV2Jets: "bkg"
    SingleTop: "bkg"
    G1Jet: "bkg"
    VGamma: "bkg"
    MET: "MET"
    SingleMuon: "SingleMuon"
    SingleElectron: "SingleElectron"
