sample_colours:
    MET:              "black"
    SingleMuon:       "black"
    SingleElectron:   "black"
    ZJetsToNuNu:      "#80b1d3"
    WJetsToLNu:       "#b3de69"
    WJetsToENu:       "#b2df8a"
    WJetsToMuNu:      "#b3de69"
    WJetsToTauLNu:    "#8dd3c7"
    WJetsToTauHNu:    "#8dd3c7"
    Diboson:          "#fdb462"
    DYJetsToLL:       "#ffed6f"
    DYJetsToEE:       "#fff6b3"
    DYJetsToMuMu:     "#ffed6f"
    DYJetsToTauLTauL: "#ffe41a"
    DYJetsToTauLTauH: "#ffe41a"
    DYJetsToTauHTauH: "#ffe41a"
    EWKV2Jets:        "#bebada"
    SingleTop:        "#fccde5"
    TTJets:           "#bc80bd"
    QCD:              "#fb8072"
    G1Jet:            "#ccebc5"
    VGamma:           "#ffffb3"
    Minor:            "#d9d9d9"
sample_names:
    MET:              "MET"
    SingleMuon:       "Single Muon"
    SingleElectron:   "Single Electron"
    ZJetsToNuNu:      "$Z_{\\nu\\nu}$+jets"
    WJetsToLNu:       "$W_{l\\nu}$+jets"
    WJetsToENu:       "$W_{e\\nu}$+jets"
    WJetsToMuNu:      "$W_{\\mu\\nu}$+jets"
    WJetsToTauLNu:    "$W_{\\tau_{l}\\nu}$+jets"
    WJetsToTauHNu:    "$W_{\\tau_{h}\\nu}$+jets"
    Diboson:          "Diboson"
    DYJetsToLL:       "$Z/\\gamma^{*}_{ll}$+jets"
    DYJetsToEE:       "$Z/\\gamma^{*}_{ee}$+jets"
    DYJetsToMuMu:     "$Z/\\gamma^{*}_{\\mu\\mu}$+jets"
    DYJetsToTauLTauL: "$Z/\\gamma^{*}_{\\tau_{l}\\tau_{l}}$+jets"
    DYJetsToTauLTauH: "$Z/\\gamma^{*}_{\\tau_{l}\\tau_{h}}$+jets"
    DYJetsToTauHTauH: "$Z/\\gamma^{*}_{\\tau_{h}\\tau_{h}}$+jets"
    EWKV2Jets:        "VBS"
    SingleTop:        "Single Top"
    TTJets:           "$t\\bar{t}$+jets"
    QCD:              "Multijet"
    G1Jet:            "$\\gamma$+jets"
    VGamma:           "$V+\\gamma$"
    Minor:            "Minors"
axis_label:
    METnoX_pt:  "$p_{\\mathrm{T}}^{\\mathrm{miss}}$ (GeV)"
    METnoX_phi: "$p_{\\mathrm{T}}^{\\mathrm{miss}}\\ \\phi$"
